# Generated by Django 5.2.11 on 2026-02-28 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vereador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_urna', models.CharField(max_length=255)),
                ('nome_completo', models.CharField(max_length=255)),
                ('partido_sigla', models.CharField(max_length=20)),
                ('partido_numero', models.IntegerField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status_eleicao', models.CharField(max_length=100)),
                ('is_reeleito', models.BooleanField(default=False)),
                ('ano_eleicao', models.IntegerField(default=2024)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vereadores', to='municipios.municipio')),
            ],
            options={
                'verbose_name': 'Vereador',
                'verbose_name_plural': 'Vereadores',
                'ordering': ['nome_urna'],
                'unique_together': {('municipio', 'nome_completo', 'ano_eleicao')},
            },
        ),
    ]
