# Generated by Django 5.2.11 on 2026-02-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0002_vereador'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='coligacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
