# Generated by Django 5.2.11 on 2026-02-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0003_vereador_coligacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='projetos_aprovados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vereador',
            name='total_projetos',
            field=models.IntegerField(default=0),
        ),
    ]
