# Generated by Django 5.2.11 on 2026-02-28 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0004_vereador_projetos_aprovados_vereador_total_projetos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoLei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_apresentacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Em tramitação', max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_autorados', to='municipios.vereador')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_lei', to='municipios.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='VotoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('ABSTENCAO', 'Abstenção')], max_length=20)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='municipios.projetolei')),
                ('vereador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histórico_votos', to='municipios.vereador')),
            ],
            options={
                'unique_together': {('projeto', 'vereador')},
            },
        ),
    ]
