# Generated by Django 5.2.11 on 2026-02-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0005_projetolei_votoprojeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetolei',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projetolei',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='projetolei',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projetolei',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
