# Generated by Django 5.2.11 on 2026-02-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contrato',
            new_name='contratos_c_municip_2454b9_idx',
            old_name='contratos_c_muni_id_9f8c33_idx',
        ),
        migrations.RenameIndex(
            model_name='contrato',
            new_name='contratos_c_data_as_00d1c7_idx',
            old_name='contratos_c_data_as_012b62_idx',
        ),
        migrations.RenameIndex(
            model_name='contrato',
            new_name='contratos_c_numero__700a8f_idx',
            old_name='contratos_c_numero__f24f8a_idx',
        ),
        migrations.AddField(
            model_name='contrato',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
